### ISSUE TITLE
Caused by: java.lang.ClassCastException: com.fasterxml.classmate.types.ResolvedRecursiveType cannot be cast to com.fasterxml.classmate.types.ResolvedObjectType

### ISSUE THREAD

**Issue by abid-khan** [spring-projects/spring-data-jpa-examples#18]
I am getting  this issue while enabling auditing.  Classes are provided below. I am using Spring boot 1.2.4.RELEASE

```java

@MappedSuperclass @EntityListeners({ AuditingEntityListener.class }) public class AbstractAuditablEntity
		extends AbstractPersistable<Long> {

	@Version @Column(name = "version") protected Long version;

	@Enumerated(EnumType.STRING) protected StatusType status;

	@Type(type = "org.jadira.usertype.dateandtime.joda.PersistentDateTime") protected DateTime createdDate;

	 @ManyToOne(fetch = FetchType.LAZY) @JoinColumn private User createdBy;

	@Type(type = "org.jadira.usertype.dateandtime.joda.PersistentDateTime") protected DateTime lastModifiedDate;

	@ManyToOne(fetch = FetchType.LAZY) @JoinColumn private User lastModifiedBy;

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public StatusType getStatus() {
		return status;
	}

	public void setStatus(StatusType status) {
		this.status = status;
	}

	public DateTime getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(DateTime createdDate) {
		this.createdDate = createdDate;
	}

	public User getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(User createdBy) {
		this.createdBy = createdBy;
	}

	public DateTime getLastModifiedDate() {
		return lastModifiedDate;
	}

	public void setLastModifiedDate(DateTime lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@PrePersist public void setCreatedDate() {
		this.createdDate = new DateTime();
		this.lastModifiedDate = new DateTime();
	}

	@PreUpdate public void setLastModifiedDate() {
		this.lastModifiedDate = new DateTime();
	}

	public User getLastModifiedBy() {
		return lastModifiedBy;
	}

	public void setLastModifiedBy(User lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}
}




 public class User extends AbstractAuditablEntity {

	@NotNull private String email;

	@NotNull private String password;

	@NotNull private String firstName;


...
}


```

On save getting below error..

````java
Caused by: java.lang.ClassCastException: com.fasterxml.classmate.types.ResolvedRecursiveType cannot be cast to com.fasterxml.classmate.types.ResolvedObjectType
	at com.fasterxml.classmate.TypeResolver._resolveSuperClass(TypeResolver.java:422)
	at com.fasterxml.classmate.TypeResolver._constructType(TypeResolver.java:395)
	at com.fasterxml.classmate.TypeResolver._fromClass(TypeResolver.java:351)
	at com.fasterxml.classmate.TypeResolver._fromAny(TypeResolver.java:299)
	at com.fasterxml.classmate.TypeResolver._fromParamType(TypeResolver.java:437)
	at com.fasterxml.classmate.TypeResolver._fromAny(TypeResolver.java:305)
	at com.fasterxml.classmate.TypeResolver._resolveSuperInterfaces(TypeResolver.java:409)
	at com.fasterxml.classmate.TypeResolver._constructType(TypeResolver.java:395)
	at com.fasterxml.classmate.TypeResolver._fromClass(TypeResolver.java:351)
	at com.fasterxml.classmate.TypeResolver.resolve(TypeResolver.java:111)
	at org.hibernate.validator.internal.util.ExecutableHelper.instanceMethodParametersResolveToSameTypes(ExecutableHelper.java:117)
	at org.hibernate.validator.internal.util.ExecutableHelper.overrides(ExecutableHelper.java:101)
	at org.hibernate.validator.internal.util.ExecutableHelper.overrides(ExecutableHelper.java:65)
	at org.hibernate.validator.internal.metadata.aggregated.ExecutableMetaData$Builder.accepts(ExecutableMetaData.java:328)
	at org.hibernate.validator.internal.metadata.aggregated.BeanMetaDataImpl$BuilderDelegate.add(BeanMetaDataImpl.java:586)
	at org.hibernate.validator.internal.metadata.aggregated.BeanMetaDataImpl$BeanMetaDataBuilder.addMetaDataToBuilder(BeanMetaDataImpl.java:500)
	at org.hibernate.validator.internal.metadata.aggregated.BeanMetaDataImpl$BeanMetaDataBuilder.add(BeanMetaDataImpl.java:494)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.createBeanMetaData(BeanMetaDataManager.java:180)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.getOrCreateBeanMetaData(BeanMetaDataManager.java:207)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.isConstrained(BeanMetaDataManager.java:151)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:193)
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:137)
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreInsert(BeanValidationEventListener.java:95)
	at org.hibernate.action.internal.EntityInsertAction.preInsert(EntityInsertAction.java:218)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:97)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:465)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:351)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1258)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.flush(AbstractEntityManagerImpl.java:1335)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:291)
	at com.sun.proxy.$Proxy119.flush(Unknown Source)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.flush(SimpleJpaRepository.java:480)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.saveAndFlush(SimpleJpaRepository.java:448)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

```

**Comment by anand1st** [comment]
I too had a similar problem. This problem didn't arise when I used JDK7. Only with JDK8
